apiVersion: apps/v1
kind: Deployment
metadata:
  name: medpact-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medpact-api
  template:
    metadata:
      labels:
        app: medpact-api
    spec:
      containers:
        - name: api
          image: ghcr.io/REPLACE_OWNER/medpact-api:latest
          ports:
            - containerPort: 5100
          envFrom:
            - secretRef:
                name: medpact-secrets
